[package]
name = "substrait-textplan"
version = "0.1.0"
edition = "2021"
authors = ["David Sisson"]
description = "Substrait textplan parser library in Rust"
license = "Apache-2.0"

[dependencies]
prost = "0.12.1"
prost-types = "0.12.1"
prost-serde = "0.3.0"
bytes = "1.5.0"
thiserror = "1.0.50"
anyhow = "1.0.75"
log = "0.4.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_bytes = "0.11"
tree-sitter = "0.20.10"
protobuf = "3.2.0"
antlr-rust = "0.3.0-beta"
bit-set = "0.5.3"

[build-dependencies]
prost-build = "0.12.1"
reqwest = { version = "0.11", features = ["blocking"] }

[dev-dependencies]
env_logger = "0.11.7"
tempfile = "3.8.1"

[lib]
name = "substrait_textplan"
crate-type = ["cdylib", "rlib"]

[features]
default = []
python = []